USE usjt_2016;

DROP TABLE TABALUNO;
DROP TABLE TABCURSO_INFOR;
DROP TABLE TABCURSO_ARTES;
DROP TABLE TABCURSO;

CREATE TABLE TABALUNO
(
  IDTABALUNO 	INTEGER 	 NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME 			VARCHAR(150) NOT NULL,
  ENDERECO 		VARCHAR(250) NOT NULL,
  TEL_NUM 		VARCHAR(20)  NOT NULL,
  EMAIL 		VARCHAR(150) NOT NULL,
  RG 			VARCHAR(15)  NOT NULL,
  CPF 			VARCHAR(14)  NOT NULL,
  LOGIN 		VARCHAR(60)  NOT NULL,
  SENHA 		VARCHAR(12)  NOT NULL
);



CREATE TABLE TABCURSO
(
  IDTABCURSO 	INTEGER 	 NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME 			VARCHAR(150) NOT NULL,
  DATA_INICIO   DATETIME NOT NULL,
  DATA_TERMINO  DATETIME NOT NULL,
  HORARIO 		VARCHAR(05) NOT NULL,
  NUM_VAGAS 	INTEGER NOT NULL,
  VALOR 		DOUBLE NOT NULL
);

CREATE TABLE TABCURSO_INFOR
(
  IDTABCURSO_INFOR 	   INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TABCURSO_IDTABCURSO  INTEGER NOT NULL,
  NUM_LABORATORIO 	   INTEGER NOT NULL,
  SOFTWARE        	   VARCHAR(250) NOT NULL,
  FOREIGN KEY (TABCURSO_IDTABCURSO) REFERENCES TABCURSO(IDTABCURSO)
);

CREATE TABLE TABCURSO_ARTES
(
  IDTABCURSO_ARTES 	   INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TABCURSO_IDTABCURSO  INTEGER NOT NULL,
  DESC_MATERIAL        VARCHAR(250),
  NOME_LIVRO       	   VARCHAR(250) NOT NULL,
  FOREIGN KEY (TABCURSO_IDTABCURSO) REFERENCES TABCURSO(IDTABCURSO)
);
